Add a flag to disable the activationid
jthomas/openwhisk-metrics pull request #2
Opened 2018-05-31 13:17 UTC by bigmianhua

Hi @jthomas, just updated the code, changes made to util.js and index.js, let me know if you have any question about it, thank you so much

2018-05-31 14:45 UTC, jthomas requested changes

2018-05-31 14:45 UTC, jthomas commented on index.js
> +metrics.config = [];
Should be an object and not an array?

2018-05-31 14:50 UTC, jthomas commented
Code LGTM (apart from that tiny change). 

Couple of things needed before we can merge.... 

- [ ] Add new tests for the `metrics/util.js` code to [here](https://github.com/jthomas/openwhisk-metrics/blob/master/test/metrics.js).
- [ ] Update [documentation](https://github.com/jthomas/openwhisk-metrics#configuration), add new section at the bottom of this configuration section.

2018-06-04 10:15 UTC, jthomas commented on test/metrics.js
> +  t.is(result, 'testNamespace.testName.testActivationId.testLabel');
Should this be 'testNamespace.testName.testLabel'?

2018-06-04 10:15 UTC, jthomas commented
Are the tests finished and ready for review? I've tried it locally but they aren't working atm.

2018-06-08 18:17 UTC, bigmianhua commented
@jthomas I have added a test code in test/metric.js to test util.label function based on config. Please let me know if I need to make any change on it. Thank you so much

2018-06-11 16:09 UTC, jthomas commented
@bigmianhua Thanks for adding the tests. Travis build is failing, can you investigate and resolve?

2018-06-11 19:17 UTC, bigmianhua commented
@jthomas Hi James, we have pushed the test code, and looks like it passes the test, let me know if there have any other issues, thank you!

2018-06-12 08:53 UTC, merged

2018-06-12 11:02 UTC, jthomas commented
Awesome. Thanks for the contribution. 💪💪💪
I've published the new library version to NPM. Thanks for the help with this feature.